/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_billing;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author   vrona
 */
public class Add_fees extends javax.swing.JFrame {

    /**
     * Creates new form Add_fees
     */                                    
    public Add_fees() {     
        initComponents();            

     displayCashFirst();
     fillComboBox();
    }
    public  void displayCashFirst()
    {
        lbl_DDNO.setVisible(false);
        lbl_ChequeNo.setVisible(false);
        lbl_bankName.setVisible(false);
        
        txt_DDNo.setVisible(false);
        txt_ChequeNo.setVisible(false);
        txt_bankName.setVisible(false);
        
    }
        public boolean validation(){
        if(txt_RecievedForm.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please enter user name");
            return false;
        }
        if(dateChooser.getDate()==null){
            JOptionPane.showMessageDialog(this, "please select a date");
            return false;
        }
        if(txt_amount.getText().equals("") || txt_amount.getText().matches("[0-9]*")==false){
            JOptionPane.showMessageDialog(this, "please enter amount in numbers");
            return false;
        }
          
        if(combo_paymentMode.getSelectedItem().toString().equalsIgnoreCase("Cheque")){
            if(txt_ChequeNo.getText().equals("")){
                JOptionPane.showMessageDialog(this, "please enter cheque no");
                return false;
            }
       
            if(txt_bankName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "please enter bank no");
                return false;
            }
        }
        
     if(combo_paymentMode.getSelectedItem().toString().equalsIgnoreCase("dd")){
            if(txt_DDNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please enter dd no");
                return false;
        }
            if(txt_bankName.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please enter bank name");
                return false;
            }}
      if(combo_paymentMode.getSelectedItem().toString().equalsIgnoreCase("Card")){
                if(txt_bankName.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "please enter bank name");
                }
            }
 
             return true; 
}
        public void fillComboBox(){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                
            }catch(Exception e){
                e.printStackTrace();
            }
                
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelsideBar = new javax.swing.JPanel();
        PanelLogout = new javax.swing.JPanel();
        btnLougout = new javax.swing.JLabel();
        PanelHome = new javax.swing.JPanel();
        btnHome1 = new javax.swing.JLabel();
        PanelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        PanelView = new javax.swing.JPanel();
        btnView = new javax.swing.JLabel();
        PanelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelparent = new javax.swing.JPanel();
        lbl_ChequeNo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_DDNO = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_GSTNo = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JTextField();
        txt_bankName = new javax.swing.JTextField();
        combo_paymentMode = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        panelChild = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_Year2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_total_words = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_Year1 = new javax.swing.JTextField();
        txt_CourseName = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_cgst = new javax.swing.JTextField();
        txt_sgst = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_total = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_remark = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_RecievedForm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_ChequeNo = new javax.swing.JTextField();
        txt_DDNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("GST   :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(102, 102, 255));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogout.setBackground(new java.awt.Color(102, 102, 255));
        PanelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelLogoutMouseExited(evt);
            }
        });

        btnLougout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLougout.setForeground(new java.awt.Color(255, 255, 255));
        btnLougout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnLougout.setText("Logout");
        btnLougout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLougoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLougoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelLogoutLayout = new javax.swing.GroupLayout(PanelLogout);
        PanelLogout.setLayout(PanelLogoutLayout);
        PanelLogoutLayout.setHorizontalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnLougout, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        PanelLogoutLayout.setVerticalGroup(
            PanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoutLayout.createSequentialGroup()
                .addComponent(btnLougout)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(PanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 700, 330, 70));

        PanelHome.setBackground(new java.awt.Color(102, 102, 255));
        PanelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelHomeMouseEntered(evt);
            }
        });

        btnHome1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome1.setText("    HOME");
        btnHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelHomeLayout = new javax.swing.GroupLayout(PanelHome);
        PanelHome.setLayout(PanelHomeLayout);
        PanelHomeLayout.setHorizontalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        PanelHomeLayout.setVerticalGroup(
            PanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeLayout.createSequentialGroup()
                .addComponent(btnHome1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(PanelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 330, 70));

        PanelEdit.setBackground(new java.awt.Color(102, 102, 255));
        PanelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelEditMouseEntered(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        btnEdit.setText("Edit Course");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelEditLayout = new javax.swing.GroupLayout(PanelEdit);
        PanelEdit.setLayout(PanelEditLayout);
        PanelEditLayout.setHorizontalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelEditLayout.setVerticalGroup(
            PanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsideBar.add(PanelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 330, 70));

        PanelView.setBackground(new java.awt.Color(102, 102, 255));
        PanelView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelViewMouseEntered(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view all record.png"))); // NOI18N
        btnView.setText("View  All  Record");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelViewLayout = new javax.swing.GroupLayout(PanelView);
        PanelView.setLayout(PanelViewLayout);
        PanelViewLayout.setHorizontalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PanelViewLayout.setVerticalGroup(
            PanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelViewLayout.createSequentialGroup()
                .addComponent(btnView)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(PanelView, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 330, 70));

        PanelBack.setBackground(new java.awt.Color(102, 102, 255));
        PanelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBackMouseExited(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back1.png"))); // NOI18N
        btnBack.setText("     Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBackLayout = new javax.swing.GroupLayout(PanelBack);
        PanelBack.setLayout(PanelBackLayout);
        PanelBackLayout.setHorizontalGroup(
            PanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBackLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        PanelBackLayout.setVerticalGroup(
            PanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBackLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(15, 15, 15))
        );

        panelsideBar.add(PanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 520, 1040));

        panelparent.setBackground(new java.awt.Color(153, 153, 255));
        panelparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ChequeNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl_ChequeNo.setText(" cheque  no.   :");
        panelparent.add(lbl_ChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Reciept no.  : SOC -");
        panelparent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Mode of Payment  :");
        panelparent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 40));

        lbl_DDNO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_DDNO.setText("DD no.   :");
        panelparent.add(lbl_DDNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date  :");
        panelparent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 120, 30));

        txt_GSTNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_GSTNo.setText("GSTN   :");
        panelparent.add(txt_GSTNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 60, 30));

        txt_receiptNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_receiptNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_receiptNoActionPerformed(evt);
            }
        });
        panelparent.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, 30));

        txt_bankName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_bankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bankNameActionPerformed(evt);
            }
        });
        panelparent.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 330, 30));

        combo_paymentMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Cheque", "Cash", "Card" }));
        combo_paymentMode.setSelectedIndex(2);
        combo_paymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_paymentModeActionPerformed(evt);
            }
        });
        panelparent.add(combo_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 30));
        panelparent.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 140, 30));

        panelChild.setBackground(new java.awt.Color(153, 153, 255));
        panelChild.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("The following  payment in the collage office for the year");
        panelChild.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 380, 30));

        txt_Year2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelChild.add(txt_Year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 100, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText(" to");
        panelChild.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 40, 30));

        txt_total_words.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total_words.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_wordsActionPerformed(evt);
            }
        });
        panelChild.add(txt_total_words, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 350, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Amount");
        panelChild.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 120, 30));

        comboCourse.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        panelChild.add(comboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Roll No. :  ");
        panelChild.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 120, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jSeparator2MouseEntered(evt);
            }
        });
        panelChild.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 860, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("SGST    9 %");
        panelChild.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Remark  :");
        panelChild.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Head");
        panelChild.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 120, 30));

        txt_Year1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Year1ActionPerformed(evt);
            }
        });
        panelChild.add(txt_Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 90, 40));

        txt_CourseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_CourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CourseNameActionPerformed(evt);
            }
        });
        panelChild.add(txt_CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 380, 40));

        txt_amount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        panelChild.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 240, 30));

        txt_cgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cgstActionPerformed(evt);
            }
        });
        panelChild.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 240, 30));

        txt_sgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_sgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sgstActionPerformed(evt);
            }
        });
        panelChild.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panelChild.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 310, 10));

        txt_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        panelChild.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 240, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Sr. No.");
        panelChild.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Receiver  Signature");
        panelChild.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 170, 30));

        txt_remark.setColumns(20);
        txt_remark.setRows(5);
        jScrollPane1.setViewportView(txt_remark);

        panelChild.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 360, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Total in word   :");
        panelChild.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 30));

        btn_print.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        panelChild.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 110, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelChild.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 860, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panelChild.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 310, 10));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Course  ");
        panelChild.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("CGST    9 %");
        panelChild.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 130, 30));

        txt_RecievedForm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelChild.add(txt_RecievedForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 320, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Recieved  Form  :");
        panelChild.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 30));

        panelparent.add(panelChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1310, 800));

        lbl_bankName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl_bankName.setText("Bank  Name  :  ");
        panelparent.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 30));

        txt_ChequeNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelparent.add(txt_ChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, -1));

        txt_DDNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        panelparent.add(txt_DDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("GSTN   :");
        panelparent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 60, 30));

        getContentPane().add(panelparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1410, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogoutMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_PanelLogoutMouseEntered

    private void btnLougoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLougoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        PanelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLougoutMouseEntered

    private void btnHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome1MouseEntered
        // TODO add your handling code here:
         Color clr=new Color(204,204,255);
        PanelHome.setBackground(clr);
    }//GEN-LAST:event_btnHome1MouseEntered

    private void PanelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHomeMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PanelHomeMouseEntered

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(204,204,255);
        PanelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseEntered

    private void PanelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEditMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_PanelEditMouseEntered

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(204,204,255);
        PanelView.setBackground(clr);
    }//GEN-LAST:event_btnViewMouseEntered

    private void PanelViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelViewMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_PanelViewMouseEntered

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        PanelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void PanelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBackMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PanelBackMouseEntered

    private void btnHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome1MouseExited
        // TODO add your handling code here:
       Color clr=new Color(153,153,255);
        PanelHome.setBackground(clr);
    }//GEN-LAST:event_btnHome1MouseExited

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
       Color clr=new Color(153,153,255);
        PanelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        // TODO add your handling code here:
        
         Color clr=new Color(153,153,255);
        PanelView.setBackground(clr);
    }//GEN-LAST:event_btnViewMouseExited

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr=new Color(153,153,255);
        PanelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLougoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLougoutMouseExited
        // TODO add your handling code here:
         Color clr=new Color(153,153,255);
        PanelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLougoutMouseExited

    private void PanelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBackMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PanelBackMouseExited

    private void PanelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLogoutMouseExited
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_PanelLogoutMouseExited

    private void txt_receiptNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_receiptNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_receiptNoActionPerformed

    private void txt_total_wordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_wordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_wordsActionPerformed

    private void txt_Year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Year1ActionPerformed

    private void txt_CourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CourseNameActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
       float amnt = Float.parseFloat( txt_amount.getText());
       
         Float cgst=(float)(amnt * 0.09);
         Float sgst=(float)(amnt * 0.09);
         
         txt_cgst.setText(cgst.toString());
         txt_sgst.setText(sgst.toString());
         
         float total= amnt + cgst + sgst;
        txt_total.setText(Float.toString(total));
        
         txt_total_words.setText(NumberToWordConverter.convert((int)total)+"" + "only");
       
        
    }//GEN-LAST:event_txt_amountActionPerformed

    private void txt_cgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cgstActionPerformed

    private void txt_sgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sgstActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        if(validation()==true){
            JOptionPane.showMessageDialog(this, "validation  successful");
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void txt_bankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bankNameActionPerformed

    private void combo_paymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_paymentModeActionPerformed
        // TODO add your handling code here:
        if (combo_paymentMode.getSelectedIndex()==0){
            
            lbl_DDNO.setVisible  (true);
            txt_DDNo.setVisible  (true);
            lbl_ChequeNo.setVisible(false);
            txt_ChequeNo.setVisible(false);
            lbl_bankName.setVisible(true);
            txt_bankName.setVisible(true);
            
        }
        if (combo_paymentMode.getSelectedIndex()==1){
            
            lbl_DDNO.setVisible  (false);
            txt_DDNo.setVisible  (false);
            lbl_ChequeNo.setVisible(true);
            txt_ChequeNo.setVisible(true);
            lbl_bankName.setVisible(true);
            txt_bankName.setVisible(true);
            
        }
         if (combo_paymentMode.getSelectedIndex()==2){
            
            lbl_DDNO.setVisible  (false);
            txt_DDNo.setVisible  (false);
            lbl_ChequeNo.setVisible(false);
            txt_ChequeNo.setVisible(false);
            lbl_bankName.setVisible(false);
            txt_bankName.setVisible(false);
            
        }
         if (combo_paymentMode.getSelectedItem().equals("Card")){
            
            lbl_DDNO.setVisible  (false);
            txt_DDNo.setVisible  (false);
            lbl_ChequeNo.setVisible(false);
            txt_ChequeNo.setVisible(false);
            lbl_bankName.setVisible(true);
            txt_bankName.setVisible(true);
            
        }
    }//GEN-LAST:event_combo_paymentModeActionPerformed

    private void jSeparator2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator2MouseEntered
        // TODO add your handling code here:
         Color clr=new Color(0,0,0);
        jSeparator2.setBackground(clr);
    }//GEN-LAST:event_jSeparator2MouseEntered
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBack;
    private javax.swing.JPanel PanelEdit;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelLogout;
    private javax.swing.JPanel PanelView;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHome1;
    private javax.swing.JLabel btnLougout;
    private javax.swing.JLabel btnView;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JComboBox<String> combo_paymentMode;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_ChequeNo;
    private javax.swing.JLabel lbl_DDNO;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JPanel panelChild;
    private javax.swing.JPanel panelparent;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTextField txt_ChequeNo;
    private javax.swing.JTextField txt_CourseName;
    private javax.swing.JTextField txt_DDNo;
    private javax.swing.JLabel txt_GSTNo;
    private javax.swing.JTextField txt_RecievedForm;
    private javax.swing.JTextField txt_Year1;
    private javax.swing.JTextField txt_Year2;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bankName;
    private javax.swing.JTextField txt_cgst;
    private javax.swing.JTextField txt_receiptNo;
    private javax.swing.JTextArea txt_remark;
    private javax.swing.JTextField txt_sgst;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_total_words;
    // End of variables declaration//GEN-END:variables
}
