package fees_billing;
import fees_billing.NumberToWordConverter;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vrona
 */
public class AddFees extends javax.swing.JFrame {

    /**
     * Creates new form AddFees
     */
    public AddFees() {
        initComponents();
        displayCashFirst();
    }
    public void displayCashFirst(){
        lbl_DDno.setVisible(false);
        lbl_checkNo.setVisible(false);
        lbl_bankname.setVisible(false);
        
        txt_DDNo.setVisible(false);
        txt_checkno.setVisible(false);
        txt_bankName.setVisible(false);
    }
    public boolean validation(){
        if(txt_receivedFrom.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please enter user name");
            return false;
        }
        if(datechooser.getDate()==null){
            JOptionPane.showMessageDialog(this, "please select a date");
            return false;
        }
        if(txt_amount.getText().equals("") || txt_amount.getText().matches("[0-9]*")==false){
            JOptionPane.showMessageDialog(this, "please enter amount in numbers");
            return false;
        }
        if(combo_paymentmode.getSelectedItem().toString().equalsIgnoreCase("Check")){
            if(txt_checkno.getText().equals("")){
                JOptionPane.showMessageDialog(this, "please enter cheque no");
                return false;
            }
            if(txt_bankName.getText().equals("")){
                JOptionPane.showMessageDialog(this, "please enter bank no");
                return false;
            }
        }
        
     if(combo_paymentmode.getSelectedItem().toString().equalsIgnoreCase("dd")){
            if(txt_DDNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please enter dd no");
                return false;
        }
            if(txt_bankName.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please enter bank name");
                return false;
            }}
      if(combo_paymentmode.getSelectedItem().toString().equalsIgnoreCase("card")){
                if(txt_bankName.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "please enter bank name");
                }
            }
        
        return true;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btnHome1 = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btnHome2 = new javax.swing.JLabel();
        btnHome3 = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btnHome4 = new javax.swing.JLabel();
        btnHome5 = new javax.swing.JLabel();
        panelHome3 = new javax.swing.JPanel();
        btnHome6 = new javax.swing.JLabel();
        btnHome7 = new javax.swing.JLabel();
        btnHome8 = new javax.swing.JLabel();
        panelHome4 = new javax.swing.JPanel();
        btnHome9 = new javax.swing.JLabel();
        btnHome10 = new javax.swing.JLabel();
        panelHome5 = new javax.swing.JPanel();
        btnHome11 = new javax.swing.JLabel();
        btnHome12 = new javax.swing.JLabel();
        panelHome6 = new javax.swing.JPanel();
        btnHome13 = new javax.swing.JLabel();
        btnHome14 = new javax.swing.JLabel();
        panelHome7 = new javax.swing.JPanel();
        btnHome15 = new javax.swing.JLabel();
        btnHome16 = new javax.swing.JLabel();
        btnHome17 = new javax.swing.JLabel();
        panelsearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        panelCourselist = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnlogout = new javax.swing.JLabel();
        panelParent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_DDno = new javax.swing.JLabel();
        lbl_checkNo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_GSTNo = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_recieptNO = new javax.swing.JTextField();
        txt_DDNo = new javax.swing.JTextField();
        txt_checkno = new javax.swing.JTextField();
        datechooser = new com.toedter.calendar.JDateChooser();
        panel_child = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Year2 = new javax.swing.JTextField();
        txt_totalword = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Year1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        txt_cgst = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txt_sgst = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JTextField();
        combo_paymentmode = new javax.swing.JComboBox<>();
        txt_bankName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(153, 153, 255));
        panelsideBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(153, 153, 255));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome1.setText("Home");
        panelHome.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome1.setBackground(new java.awt.Color(153, 153, 255));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome2.setForeground(new java.awt.Color(255, 255, 255));
        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome2.setText("Home");
        btnHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome2MouseExited(evt);
            }
        });
        panelHome1.add(btnHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome3.setForeground(new java.awt.Color(255, 255, 255));
        btnHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome3.setText("Home");
        panelHome1.add(btnHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome2.setBackground(new java.awt.Color(153, 153, 255));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome4.setForeground(new java.awt.Color(255, 255, 255));
        btnHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome4.setText("Home");
        btnHome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome4MouseExited(evt);
            }
        });
        panelHome2.add(btnHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome5.setForeground(new java.awt.Color(255, 255, 255));
        btnHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome5.setText("Home");
        panelHome2.add(btnHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome3.setBackground(new java.awt.Color(153, 153, 255));
        panelHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome6.setForeground(new java.awt.Color(255, 255, 255));
        btnHome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome6.setText("Home");
        btnHome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome6MouseExited(evt);
            }
        });
        panelHome3.add(btnHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome7.setForeground(new java.awt.Color(255, 255, 255));
        btnHome7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome7.setText("Home");
        panelHome3.add(btnHome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome2.add(panelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        panelHome1.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        panelHome.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        btnHome8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome8.setForeground(new java.awt.Color(255, 255, 255));
        btnHome8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome8.setText("Home");
        btnHome8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome8MouseExited(evt);
            }
        });
        panelHome.add(btnHome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome4.setBackground(new java.awt.Color(153, 153, 255));
        panelHome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome9.setForeground(new java.awt.Color(255, 255, 255));
        btnHome9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome9.setText("Home");
        btnHome9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome9MouseExited(evt);
            }
        });
        panelHome4.add(btnHome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome10.setForeground(new java.awt.Color(255, 255, 255));
        btnHome10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome10.setText("Home");
        panelHome4.add(btnHome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome5.setBackground(new java.awt.Color(153, 153, 255));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome11.setForeground(new java.awt.Color(255, 255, 255));
        btnHome11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome11.setText("Home");
        btnHome11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome11MouseExited(evt);
            }
        });
        panelHome5.add(btnHome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome12.setForeground(new java.awt.Color(255, 255, 255));
        btnHome12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome12.setText("Home");
        panelHome5.add(btnHome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome6.setBackground(new java.awt.Color(153, 153, 255));
        panelHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome13.setForeground(new java.awt.Color(255, 255, 255));
        btnHome13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome13.setText("Home");
        btnHome13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome13MouseExited(evt);
            }
        });
        panelHome6.add(btnHome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome14.setForeground(new java.awt.Color(255, 255, 255));
        btnHome14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome14.setText("Home");
        panelHome6.add(btnHome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome7.setBackground(new java.awt.Color(153, 153, 255));
        panelHome7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome15.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome15.setForeground(new java.awt.Color(255, 255, 255));
        btnHome15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome15.setText("Home");
        btnHome15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome15MouseExited(evt);
            }
        });
        panelHome7.add(btnHome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        btnHome16.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome16.setForeground(new java.awt.Color(255, 255, 255));
        btnHome16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome16.setText("Home");
        panelHome7.add(btnHome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome6.add(panelHome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        panelHome5.add(panelHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        panelHome4.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        btnHome17.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnHome17.setForeground(new java.awt.Color(255, 255, 255));
        btnHome17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome17.setText("Home");
        btnHome17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHome17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHome17MouseExited(evt);
            }
        });
        panelHome4.add(btnHome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 210, -1));

        panelHome.add(panelHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 70));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 320, 70));

        panelsearch.setBackground(new java.awt.Color(153, 153, 255));
        panelsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelsearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        btnSearch.setText("Search record");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        panelsearch.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        panelsideBar.add(panelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 320, 60));

        panelEdit.setBackground(new java.awt.Color(153, 153, 255));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        btnEdit.setText("Edit Course");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnEdit)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addComponent(btnEdit)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelsideBar.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 320, 70));

        panelCourselist.setBackground(new java.awt.Color(153, 153, 255));
        panelCourselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCourseList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N
        btnCourseList.setText("Course list");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCourselistLayout = new javax.swing.GroupLayout(panelCourselist);
        panelCourselist.setLayout(panelCourselistLayout);
        panelCourselistLayout.setHorizontalGroup(
            panelCourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCourselistLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(btnCourseList, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelCourselistLayout.setVerticalGroup(
            panelCourselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCourseList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        panelsideBar.add(panelCourselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 320, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(153, 153, 255));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnViewAllRecord.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelViewAllRecordLayout = new javax.swing.GroupLayout(panelViewAllRecord);
        panelViewAllRecord.setLayout(panelViewAllRecordLayout);
        panelViewAllRecordLayout.setHorizontalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewAllRecordLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnViewAllRecord)
                .addGap(58, 58, 58))
        );
        panelViewAllRecordLayout.setVerticalGroup(
            panelViewAllRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewAllRecordLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnViewAllRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 320, -1));

        panelBack.setBackground(new java.awt.Color(153, 153, 255));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back1.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 320, 50));

        panelLogout.setBackground(new java.awt.Color(153, 153, 255));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoutLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btnlogout)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1040));

        panelParent.setBackground(new java.awt.Color(204, 204, 255));
        panelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mode of payment :");
        panelParent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lbl_DDno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DDno.setText("DD no :");
        panelParent.add(lbl_DDno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lbl_checkNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_checkNo.setText("Check No :");
        panelParent.add(lbl_checkNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Recipt no : soc ");
        panelParent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txt_GSTNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_GSTNo.setText("31Hg23");
        panelParent.add(txt_GSTNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        lbl_bankname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bankname.setText("Bank Name :");
        panelParent.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Date :");
        panelParent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("GST54 :");
        panelParent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("GST54 :");
        panelParent.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        txt_recieptNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelParent.add(txt_recieptNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 160, -1));

        txt_DDNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelParent.add(txt_DDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, -1));

        txt_checkno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelParent.add(txt_checkno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, -1));
        panelParent.add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 130, -1));

        panel_child.setBackground(new java.awt.Color(204, 204, 255));
        panel_child.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("The following payment the college office for the year");
        panel_child.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("to");
        panel_child.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        txt_Year2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_Year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 80, -1));

        txt_totalword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_totalword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 340, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Course");
        panel_child.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        txt_Year1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 80, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Recieved From :");
        panel_child.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Recieved From :");
        panel_child.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        comboCourse.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Check", "cash", "card" }));
        panel_child.add(comboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 260, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Amount");
        panel_child.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));
        panel_child.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 1280, -1));
        panel_child.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 1280, -1));
        panel_child.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 1280, -1));
        panel_child.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 1280, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("SGST 9%");
        panel_child.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Remarks :");
        panel_child.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Head");
        panel_child.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 80, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 340, -1));

        txt_amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        panel_child.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 170, -1));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_cgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cgstActionPerformed(evt);
            }
        });
        panel_child.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 271, 170, 40));
        panel_child.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 200, 10));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 170, -1));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 170, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("S No.");
        panel_child.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Reciver signature ");
        panel_child.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panel_child.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 330, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Total in words :");
        panel_child.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_child.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Course");
        panel_child.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("CGST 9%");
        panel_child.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        txt_receivedFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panel_child.add(txt_receivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 330, -1));

        panelParent.add(panel_child, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1300, 630));

        combo_paymentmode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "Check", "cash", "card" }));
        combo_paymentmode.setSelectedIndex(2);
        combo_paymentmode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_paymentmodeActionPerformed(evt);
            }
        });
        panelParent.add(combo_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 160, 30));

        txt_bankName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelParent.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 160, -1));

        getContentPane().add(panelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 1310, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited

        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome2MouseEntered

    private void btnHome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome2MouseExited

    private void btnHome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome4MouseEntered

    private void btnHome4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome4MouseExited

    private void btnHome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome6MouseEntered

    private void btnHome6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome6MouseExited

    private void btnHome8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome8MouseEntered

    private void btnHome8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome8MouseExited

    private void btnHome9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome9MouseEntered

    private void btnHome9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome9MouseExited

    private void btnHome11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome11MouseEntered

    private void btnHome11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome11MouseExited

    private void btnHome13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome13MouseEntered

    private void btnHome13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome13MouseExited

    private void btnHome15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome15MouseEntered

    private void btnHome15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome15MouseExited

    private void btnHome17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome17MouseEntered

    private void btnHome17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome17MouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelsearch.setBackground(clr);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelCourselist.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelCourselist.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,204,255);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,153,255);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void txt_cgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cgstActionPerformed

    private void combo_paymentmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_paymentmodeActionPerformed
        // TODO add your handling code here:
        if(combo_paymentmode.getSelectedIndex() == 0){
            lbl_DDno.setVisible(true);
            txt_DDNo.setVisible(true);
            lbl_checkNo.setVisible(false);
            txt_checkno.setVisible(false);
            lbl_bankname.setVisible(true);
            txt_bankName.setVisible(true);
        }
         if(combo_paymentmode.getSelectedIndex() == 1){
            lbl_DDno.setVisible(false);
            txt_DDNo.setVisible(false);
            lbl_checkNo.setVisible(true);
            txt_checkno.setVisible(true);
            lbl_bankname.setVisible(true);
            txt_bankName.setVisible(true);
        }
         if(combo_paymentmode.getSelectedIndex() == 2){
            lbl_DDno.setVisible(false);
            txt_DDNo.setVisible(false);
            lbl_checkNo.setVisible(false);
            txt_checkno.setVisible(false);
            lbl_bankname.setVisible(false);
            txt_bankName.setVisible(false);
        }
         if(combo_paymentmode.getSelectedItem().equals("Card") ){
            lbl_DDno.setVisible(false);
            txt_DDNo.setVisible(false);
            lbl_checkNo.setVisible(false);
            txt_checkno.setVisible(false);
            lbl_bankname.setVisible(true);
            txt_bankName.setVisible(true);
        }
    }//GEN-LAST:event_combo_paymentmodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(validation()==true){
            JOptionPane.showMessageDialog(this, "validation succesfull");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        
        Float amnt=Float.parseFloat(txt_amount.getText());
//        
        Float cgst=(float)(amnt * 0.09);
        Float sgst=(float)(amnt * 0.09);
        
        txt_cgst.setText(cgst.toString());
        txt_sgst.setText(sgst.toString());
        
        float total= amnt + cgst + sgst;
        txt_total.setText(Float.toString(total));
        
         txt_totalword.setText(NumberToWordConverter.convert((int)total)+"only");
       
    }//GEN-LAST:event_txt_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHome1;
    private javax.swing.JLabel btnHome10;
    private javax.swing.JLabel btnHome11;
    private javax.swing.JLabel btnHome12;
    private javax.swing.JLabel btnHome13;
    private javax.swing.JLabel btnHome14;
    private javax.swing.JLabel btnHome15;
    private javax.swing.JLabel btnHome16;
    private javax.swing.JLabel btnHome17;
    private javax.swing.JLabel btnHome2;
    private javax.swing.JLabel btnHome3;
    private javax.swing.JLabel btnHome4;
    private javax.swing.JLabel btnHome5;
    private javax.swing.JLabel btnHome6;
    private javax.swing.JLabel btnHome7;
    private javax.swing.JLabel btnHome8;
    private javax.swing.JLabel btnHome9;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JComboBox<String> combo_paymentmode;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_DDno;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_checkNo;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourselist;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelHome3;
    private javax.swing.JPanel panelHome4;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelHome6;
    private javax.swing.JPanel panelHome7;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panel_child;
    private javax.swing.JPanel panelsearch;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTextField txt_DDNo;
    private javax.swing.JLabel txt_GSTNo;
    private javax.swing.JTextField txt_Year1;
    private javax.swing.JTextField txt_Year2;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bankName;
    private javax.swing.JTextField txt_cgst;
    private javax.swing.JTextField txt_checkno;
    private javax.swing.JTextField txt_receivedFrom;
    private javax.swing.JTextField txt_recieptNO;
    private javax.swing.JTextField txt_sgst;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_totalword;
    // End of variables declaration//GEN-END:variables
}
